### PR TITLE
Ktor 2.0.0 Upgrade

### PR DESCRIPTION
**Pull request by rbbl-dev**
upgrade to ktor 2.0.0

### CODE REVIEW

**Comment by rbbl-dev** [comment]
@mantono can i get a merge on that? :)

**Comment by mantono** [comment]
> @mantono can i get a merge on that? :)

I am sorry, I am no longer an employee of Zensum and not a maintainer of this repository anymore, so I do not have any administrator privileges.

**Comment by rbbl-dev** [comment]
do you know who is still working there?

**Comment by rbbl-dev** [comment]
@jeppesens can i get this merged?

**Comment by mantono** [comment]
> do you know who is still working there?

Maybe @ElenaKurganova or @pn can assist you 🙂

**Review by pn — APPROVED** [review]
LGTM

**Comment by ElenaKurganova** [comment]
LGTM. 

@mantono nice to see you here :-)

**Pull request merged**
