### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by MxKaras**
Simple update to refresh dependencies.

### CODE REVIEW

**Comment by Torbacka** [comment]
Thank you for this pull request. We will get back to you on Monday, but after a quick glance I can't see any problem with merging this request.

**Review by 6185541513 — APPROVED** [review]
lgtm

**Comment by MxKaras** [comment]
Am I clear to merge with 1/2 approvals?

**Comment by 6185541513** [comment]
> Am I clear to merge with 1/2 approvals?

TLDR; go for it

We don't have a clear rule on this. It can vary depending on what you're merging and wheter it affects the structure at large, then you should wait for eveyone. Sometimes it's ok to merge with only one approval from someone who has good knowledge about possible effects. In this situation I can't say I'm to be trusted to know for certain this is ok because I didn't investigate each version, but honeslty it's not that big a change, so yeah it's ok

**Comment by MxKaras** [comment]
Cool, I'm going to go for it 👍

**Comment by MxKaras** [comment]
Ah, I can't do it myself.

**Comment by 6185541513** [comment]
> Ah, I can't do it myself.

No worries, I did it now @MxKaras.

**Pull request merged**
